server:
  port: 8084
spring:
  datasource:
    #url: jdbc:h2:file:D:/Workspaces/File_DB/h2_CQRS-services
    password: cqrs
    url: jdbc:postgresql://localhost:5432/cqrs
    username: cqrs_update
  jpa:
    hibernate:
      ddl-auto: update